const fs = require('node:fs');
const path = require('node:path');
const out = path.join(__dirname, 'public');
fs.mkdirSync(out, { recursive: true });
fs.cpSync(path.join(__dirname, 'assets'), path.join(out, 'assets'), { recursive: true });
const booking = '<a class="button" href="rendez-vous.html">Prendre rendez-vous <span aria-hidden="true">↗</span></a>';
const pages = [
  ['index.html', 'Accueil', '⌂'], ['approche.html', 'Mon approche', '◯'], ['soins.html', 'Les soins', '≋'], ['cadeau.html', 'Bon cadeau', '◇'], ['rendez-vous.html', 'Rendez-vous', '▦']
];
const link = (file, label, current, icon = '') => `<a href="${file}"${file === current ? ' aria-current="page"' : ''}>${icon ? `<span aria-hidden="true">${icon}</span>` : ''}${label}</a>`;
function head(label, title, intro) {
  return `<div class="page-head"><div class="breadcrumb"><a href="index.html">Accueil</a> &nbsp; / &nbsp; ${label}</div><div class="eyebrow">${label}</div><h1>${title}</h1><p class="lead">${intro}</p></div>`;
}
const contents = {
  'index.html': `<section class="hero"><div><div class="eyebrow">Massage bien-être · Saturnain</div><h1>Moins de tensions.<br>Plus de place<br><em>pour vous.</em></h1><p class="lead">Un temps pour ralentir, relâcher et retrouver vos sensations. Des massages bien-être à votre écoute, dans un cadre simple et chaleureux.</p><div class="actions">${booking}<a class="button secondary" href="soins.html">Découvrir les soins</a></div><div class="hero-note"><b aria-hidden="true">✧</b> Une présence attentive. Un massage qui vous ressemble.</div></div><figure class="visual"><img src="assets/atelier.svg" width="1000" height="1100" alt="Illustration d’une cabine chaleureuse : table de massage, linge naturel et feuillage dans une lumière douce."><div class="pill" aria-hidden="true">RALENTIR<br>RESPIRER<br>SE RETROUVER</div><figcaption><span aria-hidden="true">☼</span> Le calme commence par un moment pour soi.</figcaption></figure></section>
  <div class="trust"><span><b aria-hidden="true">◯</b> Une écoute de vos besoins</span><span><b aria-hidden="true">≋</b> Un rythme et une pression adaptés</span><span><b aria-hidden="true">✧</b> Un cadre professionnel et respectueux</span></div>
  <section class="section"><div class="section-head"><div><div class="eyebrow">À chacun son moment</div><h2>De quoi avez-vous besoin ?</h2></div><a class="text-link" href="benefices.html">Explorer les bienfaits &nbsp; ↗</a></div><div class="cards"><article class="card"><span class="number">01 / SOUFFLER</span><h3>Le quotidien va trop vite</h3><p>Une pause loin des sollicitations, pour porter votre attention sur vos sensations et vous détendre.</p><a class="text-link" href="benefices.html#souffler">Prendre du temps pour soi ↗</a></article><article class="card"><span class="number">02 / RELÂCHER</span><h3>Le corps réclame une pause</h3><p>Après une journée chargée ou passée au bureau, retrouver une sensation de confort et de légèreté.</p><a class="text-link" href="benefices.html#relacher">Écouter son corps ↗</a></article><article class="card"><span class="number">03 / SE RETROUVER</span><h3>L’envie de se reconnecter</h3><p>Sortir du pilote automatique et s’accorder un moment où l’on n’a rien à faire, simplement à être.</p><a class="text-link" href="benefices.html#retrouver">Revenir à ses sensations ↗</a></article></div></section>
  <aside class="gift-band"><div class="gift-icon" aria-hidden="true">◇</div><div><h2>Offrez une vraie parenthèse.</h2><p>Un moment pour soi, à offrir à quelqu’un qui compte.</p></div><a class="button secondary" href="cadeau.html">Découvrir le bon cadeau ↗</a></aside>`,
  'approche.html': `${head('Mon approche', 'De l’écoute.<br>Du soin. De la simplicité.', 'Je suis Saturnain, masseuse bien-être. Mon intention : vous accueillir avec attention et faire de ce rendez-vous un moment pleinement consacré à vous.')}<div class="split"><div class="stack"><h2>Un massage se construit à deux.</h2><p>Avant la séance, nous prenons le temps d’échanger sur vos attentes et vos préférences. Pendant le massage, vous pouvez demander un ajustement de la pression, signaler une gêne ou arrêter à tout moment.</p><p>Votre confort et votre intimité guident la séance. Seules les zones massées sont découvertes, dans le respect de vos limites.</p>${booking}</div><aside class="card"><div class="eyebrow">La personne derrière les mains</div><h2>Faisons connaissance.</h2><p>Le portrait, le prénom, le parcours et les formations de votre praticienne seront présentés ici.</p><div class="notice">Première version : ce texte d’approche est une proposition éditoriale à valider avec la praticienne.</div><p>Les prestations sont des massages de bien-être, sans caractère médical, sexuel ou érotique.</p></aside></div>`,
  'benefices.html': `${head('Vos besoins', 'Un temps pour vous,<br>à votre façon.', 'Il n’y a pas besoin d’attendre d’être à bout pour s’accorder une pause. Voici trois façons d’envisager votre moment de bien-être.')}<div class="cards"><article class="card" id="souffler"><span class="number">QUOTIDIEN INTENSE</span><h2>Souffler</h2><p>Quand les journées s’enchaînent, le massage propose un cadre calme et un temps sans sollicitations. Une invitation à ralentir.</p></article><article class="card" id="relacher"><span class="number">TRAVAIL & ACTIVITÉ</span><h2>Relâcher</h2><p>Après le bureau ou une journée active, une séance peut être l’occasion de retrouver une sensation de détente corporelle, selon votre ressenti.</p></article><article class="card" id="retrouver"><span class="number">TEMPS POUR SOI</span><h2>Se retrouver</h2><p>Pour celles et ceux qui donnent beaucoup aux autres : un moment d’attention à soi et à ses sensations, sans objectif de performance.</p></article></div><div class="section"><p class="muted">Les ressentis varient d’une personne à l’autre. Un massage bien-être ne remplace pas une consultation ou un traitement médical.</p><a class="button" href="soins.html">Trouver mon moment ↗</a></div>`,
  'soins.html': `${head('Les soins', 'Le bon rythme.<br>La juste attention.', 'Des formats pour vous aider à choisir le temps que vous souhaitez vous accorder. Le catalogue ci-dessous est une proposition, à confirmer avant ouverture.')}<div class="cards"><article class="card"><span class="number">FORMAT PROPOSÉ · 30 MIN</span><h2>La pause ciblée</h2><p>Un temps court consacré aux zones de confort définies ensemble, pour une parenthèse dans votre journée.</p><p class="price">À confirmer <small>Tarif</small></p><a class="text-link" href="rendez-vous.html">Voir la réservation ↗</a></article><article class="card"><span class="number">FORMAT PROPOSÉ · 60 MIN</span><h2>La parenthèse</h2><p>Le temps de s’installer et de profiter d’un massage bien-être plus global, adapté à vos préférences.</p><p class="price">À confirmer <small>Tarif</small></p><a class="text-link" href="rendez-vous.html">Voir la réservation ↗</a></article><article class="card"><span class="number">FORMAT PROPOSÉ · 90 MIN</span><h2>Le temps long</h2><p>Une séance prolongée pour prendre le temps, avec un rythme posé et davantage de place pour vos besoins.</p><p class="price">À confirmer <small>Tarif</small></p><a class="text-link" href="rendez-vous.html">Voir la réservation ↗</a></article></div><section class="section wide"><div class="eyebrow">Votre première séance</div><h2>Comment se déroule ce moment ?</h2><details open><summary>01. Nous prenons le temps d’échanger</summary><p>Vous partagez vos attentes, vos préférences et les informations utiles à votre confort. Le format et les zones du massage sont convenus ensemble.</p></details><details><summary>02. Vous vous installez à votre rythme</summary><p>Votre intimité est préservée. Vous pouvez exprimer vos limites et demander des adaptations tout au long de la séance.</p></details><details><summary>03. Vous profitez du massage</summary><p>La pression et le rythme s’ajustent à vos retours. Vous êtes libre de parler ou de profiter du silence.</p></details><details><summary>04. Vous revenez doucement à votre journée</summary><p>Un temps de transition vous permet de vous relever tranquillement et de partager vos ressentis si vous le souhaitez.</p></details></section>`,
  'rendez-vous.html': `${head('Rendez-vous', 'Votre prochaine pause<br>commence ici.', 'Retrouvez ici les informations pratiques et, prochainement, les disponibilités pour votre massage.')}<div class="split"><section class="card"><div class="eyebrow">Agenda · Planity</div><h2>Choisir votre créneau</h2><p>L’agenda n’est pas encore connecté. Aucun créneau ne peut être réservé depuis cette première version.</p><div class="notice">Les disponibilités seront affichées ici après l’activation de l’agenda de la praticienne.</div><button class="button" disabled>Réservation bientôt disponible</button><p class="small">La réservation avec Treatwell pourra également être proposée.</p></section><section class="card"><div class="eyebrow">Informations pratiques</div><h2>Venir au cabinet</h2><p><strong>Adresse et accès</strong><br>Adresse, transports, stationnement et accessibilité à renseigner.</p><p><strong>Horaires & contact</strong><br>Horaires, téléphone et adresse e-mail à renseigner.</p><p><strong>Tarifs</strong><br>Les prix des séances sont en cours de définition.</p><a class="text-link" href="soins.html">Découvrir les formats proposés ↗</a></section></div><section class="wide"><h2>Vos retours ont leur place ici.</h2><p class="muted">Des extraits d’avis Google authentiques seront ajoutés une fois la fiche de l’établissement communiquée.</p></section>`,
'cadeau.html': `${head('Bon cadeau', 'Du temps pour soi.<br>Le plus beau des cadeaux.', 'Personnalisez une attention pour quelqu’un qui compte. L’aperçu se met à jour au fil de vos envies.')}<div class="split"><section><form id="gift-form"><label for="sender">Votre nom</label><input id="sender" name="sender" autocomplete="name" maxlength="80" placeholder="De la part de…"><label for="recipient">Le nom de la personne qui le recevra</label><input id="recipient" name="recipient" autocomplete="off" maxlength="80" placeholder="Pour…"><label for="care">Le soin à offrir</label><select id="care" name="care"><option>La pause ciblée · 30 min · Tarif à confirmer</option><option selected>La parenthèse · 60 min · Tarif à confirmer</option><option>Le temps long · 90 min · Tarif à confirmer</option></select><div class="notice">Aperçu uniquement : la vente de bons cadeaux n’est pas encore ouverte. Aucun paiement n’est effectué et vos informations ne sont pas envoyées.</div><button class="button" type="button" disabled>Paiement bientôt disponible</button><p class="small">Bon cadeau valable 6 mois à compter de la date d’achat. Pour cet aperçu, la date limite est calculée à partir d’aujourd’hui.</p></form></section><aside class="gift-preview" aria-label="Aperçu du bon cadeau"><div class="brand">saturnain<span>Massage bien-être</span></div><h2>Une parenthèse<br>rien que pour vous.</h2><p>Pour <strong id="preview-to">Une personne qui compte</strong></p><hr><p id="preview-care">La parenthèse · 60 min · Tarif à confirmer</p><p class="small">De la part de <span id="preview-from">Vous</span></p><p>Valable jusqu’au <time id="preview-expiry">terme des 6 mois suivant l’achat</time> inclus.</p><p class="small">APERÇU · SANS VALEUR D’ACHAT</p></aside></div>`,
  'informations.html': `${head('Informations', 'En toute transparence.', 'Ce site est une première version de présentation, en cours de préparation.')}<div class="wide"><h2>Éditeur & hébergement</h2><p>L’identité complète de l’éditeur, son adresse professionnelle, ses coordonnées, les informations d’entreprise applicables et l’hébergeur restent à renseigner avant publication.</p><h2>Vos données</h2><p>Cette version ne contient aucun outil de mesure d’audience et ne transmet pas les noms saisis dans l’aperçu du bon cadeau. Le choix du thème est enregistré dans votre navigateur uniquement.</p><p>Les règles relatives aux services de réservation et de paiement seront précisées lors de leur activation.</p><h2>Cadre des prestations</h2><p>Massages de bien-être à visée de détente, sans caractère médical, sexuel ou érotique. Les prestations, tarifs et conditions de vente sont à confirmer.</p><h2>Crédits</h2><p>Illustration originale de cabine réalisée pour cette maquette. Elle ne représente pas le cabinet réel.</p></div>`
};
for (const [file, body] of Object.entries(contents)) {
  const label = pages.find(p => p[0] === file)?.[1] || (file === 'benefices.html' ? 'Vos besoins' : 'Informations');
  const html = `<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="robots" content="noindex,nofollow"><title>${label} — Saturnain · Massage bien-être</title><meta name="description" content="Saturnain, massage bien-être : une écoute attentive, des soins adaptés à vos envies et une parenthèse pour vous."><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/site.css"><script src="assets/site.js" defer></script></head><body><a class="skip" href="#contenu">Aller au contenu</a><header class="header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="Saturnain, accueil">saturnain<span>Massage bien-être</span></a><nav class="desktop-nav" aria-label="Navigation principale">${pages.slice(1,4).map(p => link(p[0],p[1],file)).join('')}</nav><button class="theme" id="theme" aria-label="Activer le thème sombre" aria-pressed="false">☾</button><a class="button top-book" href="rendez-vous.html"${file === 'rendez-vous.html' ? ' aria-current="page"' : ''}>Prendre rendez-vous ↗</a></div></header><noscript><div class="no-js">La navigation fonctionne sans JavaScript. Activez-le pour changer de thème et personnaliser l’aperçu du bon cadeau.</div></noscript><main id="contenu" class="wrap">${body}</main><footer><div class="wrap footer-inner"><a class="brand" href="index.html">saturnain</a><span>Un moment pour soi, tout simplement.</span><a href="informations.html">Informations & confidentialité</a><span>© ${new Date().getFullYear()} Saturnain</span></div></footer><nav class="mobile-nav" aria-label="Navigation mobile">${pages.map(p => link(p[0],p[1] === 'Mon approche' ? 'À propos' : p[1],file,p[2])).join('')}</nav></body></html>`;
  fs.writeFileSync(path.join(out, file), html);
}
console.log(`${Object.keys(contents).length} pages générées dans public/`);
